services:
    ovh_domain_editor:
        build: ..
        restart: always

        volumes:
            - ./app:/usr/src/app
            - /var/run/docker.sock:/var/run/docker.sock

        environment:
            - PYTHONUNBUFFERED=1

            - DOMAIN_NAME=asemo.pro
            - TARGET=vps01.omesa.net.
            - APPLICATION_KEY=338dc141982979a1
            - APPLICATION_SECRET=46d4e99be6450d788aa8404f1fa78fe2
            - CONSUMER_KEY=4fcd46941d35eeec0cb200ca8954f765
