services:
    domain_manager:
        build: .
        restart: always
        env_file:
            - .env
        volumes:
            - ./src:/usr/src/app/src
            - /var/run/docker_handler.sock:/var/run/docker_handler.sock
        environment:
            - PYTHONUNBUFFERED=1
