services:
  domain_manager:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      #- ./src:/usr/src/app:ro
      - /var/run/docker.sock:/var/run/docker.sock